name: Publish package

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Notify via Slack
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          pypi_project_name: reddit-graph-releases
        uses: fedecalendino/slack-release-notifier@v1.2.1
